const people = [
 
  {
    name: "Donald Trump",
    gender: "Male",
    region: "North East",
    jobRole: "Data Analyst",
    industry: "Sport",
    whyALevelMaths: "I liked statistics and wanted a subject that would be useful with lots of degree choices.",
    otherALevels: "Computer Science, Physics",
    enjoyed: "I enjoyed using data to spot patterns and make predictions.",
    usesMaths: "I analyse player performance, compare trends, and create reports for coaches.",
    anythingElse: "Being confident with numbers gives you a real advantage.",
    image: "images/donaldtrump.jpg",
    imagePosition: "center 20%",
  },
  
  {
    name: "David Beckham",
    gender: "Male",
    region: "London",
    jobRole: "Software Developer",
    industry: "Technology",
    whyALevelMaths: "I chose A Level Maths because I enjoyed logical thinking and knew it would support computer science.",
    otherALevels: "Further Maths, Psychology",
    enjoyed: "I enjoyed pure maths, especially algebra and functions.",
    usesMaths: "I use maths when writing algorithms, testing systems, and understanding performance.",
    anythingElse: "The problem-solving mindset is just as important as the content.",
    image: "images/davidbeckham.jpg",
      imagePosition: "center 20%",
  },
  
  {
    name: "Peppa Pig",
    gender: "Female",
    region: "East Midlands",
    jobRole: "Environmental Scientist",
    industry: "Environment",
    whyALevelMaths: "I cared about climate and sustainability, and maths helped me understand the science behind it.",
    otherALevels: "Computer Science, Economics",
    enjoyed: "I liked modelling and seeing how equations could describe real situations.",
    usesMaths: "I use data analysis, graphs and modelling to understand environmental change.",
    anythingElse: "Maths helps you ask better questions about the world.",
    image: "images/peppapig.jpeg",
    imagePosition: "center 20%",
  },
  
    {
    name: "Jim Hardy",
    gender: "Male",
    region: "East Midlands",
    jobRole: "Teacher",
    industry: "Education & Training",
    whyALevelMaths: "I always enjoyed Maths, and knew it would be valuable in my other A Levels and future pathways",
    otherALevels: "Physics, Electronics, Further Maths",
    enjoyed: "Small class sizes, the satisfaction of solving a problem, feeling clever!",
    usesMaths: "I'm a maths teacher, so I use it everyday :-)",
    anythingElse: "I hope you enjoy using this site.",
    image: "images/jimhardy.jpg",
    imagePosition: "center 20%",
  }
];
